<a href="https://colab.research.google.com/github/Meetchau/Meetchau/blob/main/Practise0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
a = "abkfdjbafkljasklj"

In [ ]:
a[5]

'j'

In [ ]:
a[1:4]

'bkf'

In [ ]:
a[:]

'abkfdjbafkljasklj'

In [ ]:
b = [1,2,2,3,'j']

In [ ]:
b.append('K')

In [ ]:
b

[1, 2, 2, 3, 'j', 'K']

In [ ]:
b.append(7)
b

[1, 2, 2, 3, 'j', 'K', 7, 7, 7, 7, 7]

In [ ]:
b[5] = [4,3,2]

In [ ]:
b

[1, 2, 2, 3, 'j', [4, 3, 2], 7, 7, 7, 7, 7]

In [ ]:
b[5][0]

4

In [ ]:
c = {'student0':'Jane', 'student1':'John','student2': 'Swit'}

In [ ]:
c['student0']

'Jane'

In [ ]:
k = {'Student4':{'Student':'Guy'}}

In [ ]:
k['Student4']['Student']

'Guy'

In [ ]:
x = (2,12,33,4)

In [ ]:
h = {2323,2323,2341,22,2,2,2,34}

In [ ]:
h

{2, 22, 34, 2323, 2341}

In [ ]:
y = [1,2,3,4]
for i in y:
  print('Python {}'.format(i))

Python 1
Python 2
Python 3
Python 4


In [ ]:
a = 1
while a<25:
  print("Python")
  a = a+1

Python
Python
Python
Python
Python
Python
Python
Python
Python
Python
Python
Python
Python
Python
Python
Python
Python
Python
Python
Python
Python
Python
Python
Python


In [ ]:
'king'.upper()

'KING'

In [ ]:
'KING'.lower()

'king'

In [ ]:
def cube(a):
  print(a**3)


In [ ]:
cube(5)

125


In [ ]:
cube(3)

27


In [ ]:
cube(5)

125


In [ ]:
def cuberoot(k):
  print(k**(1/3))

In [ ]:
cuberoot(27)

3.0


In [ ]:
##NUMPY

In [ ]:
import numpy as np
np.linspace(1,7,10)

array([1.        , 1.66666667, 2.33333333, 3.        , 3.66666667,
       4.33333333, 5.        , 5.66666667, 6.33333333, 7.        ])

In [ ]:
np.random.rand(3,3)

array([[0.78129413, 0.47483078, 0.83829729],
       [0.6661629 , 0.28125161, 0.3940937 ],
       [0.05476781, 0.59888692, 0.40959898]])

In [ ]:
np.random.randn(2,3)

array([[-0.47762021, -0.62734676, -0.04395103],
       [-1.21667473,  1.71444684,  0.7231334 ]])

In [ ]:
np.random.randint(12,25)

23

In [ ]:
np.random.randint(12,25,5)

array([19, 13, 23, 23, 21])

In [ ]:
r = np.random.randint(1,100,27)
r

array([98, 61, 58,  6, 42, 41, 32, 60, 12, 58, 62, 44, 12, 76, 46, 69, 82,
       27, 77, 86, 59, 50, 69, 68, 70, 12, 71])

In [ ]:
r.reshape(9,3)

array([[98, 61, 58],
       [ 6, 42, 41],
       [32, 60, 12],
       [58, 62, 44],
       [12, 76, 46],
       [69, 82, 27],
       [77, 86, 59],
       [50, 69, 68],
       [70, 12, 71]])

In [ ]:
r[0:5] = 100

In [ ]:
r

array([100, 100, 100, 100, 100,  41,  32,  60,  12,  58,  62,  44,  12,
        76,  46,  69,  82,  27,  77,  86,  59,  50,  69,  68,  70,  12,
        71])

In [ ]:
x = r.copy()

In [ ]:
x

array([100, 100, 100, 100, 100,  41,  32,  60,  12,  58,  62,  44,  12,
        76,  46,  69,  82,  27,  77,  86,  59,  50,  69,  68,  70,  12,
        71])

In [ ]:
x[:]= 0
x

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0])

In [ ]:
print(x)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [ ]:
c = np.array([[1,2,3],[2,3,4],[5,6,7]])
c

array([[1, 2, 3],
       [2, 3, 4],
       [5, 6, 7]])

In [ ]:
c[2,2]

7

In [ ]:
c[:3,1:]

array([[2, 3],
       [3, 4],
       [6, 7]])

In [ ]:
y = x<1


In [ ]:
y

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True])

In [ ]:
 k = np.random.randint(1,55,7)

In [ ]:
k

array([ 1,  2, 21, 43, 16, 16, 52])

In [ ]:
np.sqrt(k)

array([1.        , 1.41421356, 4.58257569, 6.55743852, 4.        ,
       4.        , 7.21110255])

In [ ]:
np.sin(k)

array([ 0.84147098,  0.90929743,  0.83665564, -0.83177474, -0.28790332,
       -0.28790332,  0.98662759])

In [ ]:
k

array([ 1,  2, 21, 43, 16, 16, 52])

In [ ]:
l = np.tan(k)
l

array([ 1.55740772, -2.18503986, -1.52749853, -1.49838734,  0.30063224,
        0.30063224, -6.05327238])

In [ ]:
l

array([ 1.55740772, -2.18503986, -1.52749853, -1.49838734,  0.30063224,
        0.30063224, -6.05327238])

In [ ]:
np.log(k)

array([0.        , 0.69314718, 3.04452244, 3.76120012, 2.77258872,
       2.77258872, 3.95124372])